name: m3_app
description: "A m3 app project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  go_router: ^14.3.0
  drift: ^2.20.3
  material_symbols_icons: ^4.2785.1
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.8
  flutter_pdfview: ^1.3.4
  sqlite3_flutter_libs: ^0.5.32

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  pedantic_mono: ^1.29.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  retrofit_generator: ^9.1.2
  drift_dev: ^2.20.3
  test: ^1.25.7
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
