// Mocks generated by Mockito 5.4.6 from annotations
// in m3_app/test/repository/circle_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:m3_app/infrastructure/http/circle_api/circle_api_service.dart'
    as _i3;
import 'package:m3_app/infrastructure/model/circle_api_response/circle_api_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCircleApiResponse_0 extends _i1.SmartFake
    implements _i2.CircleApiResponse {
  _FakeCircleApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CircleApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCircleApiService extends _i1.Mock implements _i3.CircleApiService {
  @override
  _i4.Future<_i2.CircleApiResponse> getLatestEventCircles(String? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestEventCircles,
          [event],
        ),
        returnValue:
            _i4.Future<_i2.CircleApiResponse>.value(_FakeCircleApiResponse_0(
          this,
          Invocation.method(
            #getLatestEventCircles,
            [event],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.CircleApiResponse>.value(_FakeCircleApiResponse_0(
          this,
          Invocation.method(
            #getLatestEventCircles,
            [event],
          ),
        )),
      ) as _i4.Future<_i2.CircleApiResponse>);
}
